<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLRLAP653" ignored="0" name="My test" tests="9" failures="2" timestamp="22 Jan 2019 14:10:58 GMT" time="0.192" errors="0">
  <testcase name="test1" time="0.034" classname="runfailedtest1.SampleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="runfailedtest1.SampleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="runfailedtest1.SampleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="runfailedtest1.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [Hi] but found [hi]">
      <![CDATA[java.lang.AssertionError: expected [Hi] but found [hi]
	at runfailedtest1.SampleTest.test1(SampleTest.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="runfailedtest1.SampleTest"/>
  <testcase name="test3" time="0.004" classname="runfailedtest1.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.006" classname="runfailedtest1.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.003" classname="runfailedtest1.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.003" classname="runfailedtest1.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [6] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [5]
	at runfailedtest1.SampleTest.test3(SampleTest.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- My test -->
